<a href="https://colab.research.google.com/github/iamatul1214/Pytorch/blob/main/Linear_regression_using_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
## To check the GPU allocated
!nvidia-smi

Mon Mar  7 18:08:18 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P8    32W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [5]:
## We have got Tesla K80 GPU

## Let's create a sample dataset with 4 features and two labels.
### Features- Region, Temperature, Rainfall, humidity
### Label- Production of wheat, production of rice.
## Here we have two labels in same data so we will have two different equations for each label. 
### y1 (Prod. of wheat)=w11*temp + w12*rainfall + w13*humidity + bias1
### y2 (Prod. of Rice)=w21*temp + w22*rainfall + w23*humidity + bias2


In [6]:
import numpy as np
import torch

In [16]:
## Let's create input data
input=np.array([[32,55,77],
                [82,15,37],
                [72,74,90],
                [34,56,90],
                [67,32,45],
                [91,90,45],], dtype='float32')        ## We can take float64 as well, but in order to save memory we are taking float32
input

array([[32., 55., 77.],
       [82., 15., 37.],
       [72., 74., 90.],
       [34., 56., 90.],
       [67., 32., 45.],
       [91., 90., 45.]], dtype=float32)

In [15]:
## Let's create the target data of label
target=np.array([[32,44],
                 [78,61],
                 [90,71],
                 [74,32],
                 [36,32],
                 [22,69]], dtype='float32')
target

array([[32., 44.],
       [78., 61.],
       [90., 71.],
       [74., 32.],
       [36., 32.],
       [22., 69.]], dtype=float32)

In [17]:
## Now we need to convert input and target to tensors because we are going to work with pytorch. Pytorch and Tensorflow required tensors only because they also work on GPU

input=torch.from_numpy(input)
target=torch.from_numpy(target)

print(input)
print(target)

tensor([[32., 55., 77.],
        [82., 15., 37.],
        [72., 74., 90.],
        [34., 56., 90.],
        [67., 32., 45.],
        [91., 90., 45.]])
tensor([[32., 44.],
        [78., 61.],
        [90., 71.],
        [74., 32.],
        [36., 32.],
        [22., 69.]])
