<a href="https://colab.research.google.com/github/iamatul1214/Pytorch/blob/main/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch     ## There are cpu and GPU versions of Pytorch. Right now we are working on GPU pytorch.

In [4]:
## Tensors in pytorch -- A tensor is also known as a matrix/vector or n dimensional array.
t1=torch.tensor(4.)
t1

tensor(4.)

In [6]:
print(type(t1))
print(type(4.))

<class 'torch.Tensor'>
<class 'float'>


In [8]:
t1.dtype

torch.float32

In [11]:
## Vector

t2=torch.tensor([1.,2.,3.,4.])
print(t2)
print(t2.dtype)


tensor([1., 2., 3., 4.])
torch.float32


In [13]:
## Matrix
t3=torch.tensor(
    [
     [1,2,3],
     [4,5,6]
     ]
)
print(t3)
print(type(t3))

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>


## Tensors don't support the string values that's why we try to convert everything into numbers when dealing with tensors

In [14]:
t4=torch.tensor([
                 [1,2,3],
                 [4,5,6],

                 [7,8,9]
])

print(t4)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [15]:
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)

torch.Size([])
torch.Size([4])
torch.Size([2, 3])
torch.Size([3, 3])


In [19]:
##Pytorch supports Autograd-> Which means it can find the gradient automatically. Here w=weight and b=bias are only trainable paramters hence, we apply requires_grad=True in them only
x=torch.tensor(3)
w=torch.tensor(4., requires_grad=True)
b=torch.tensor(5., requires_grad=True)

x,w,b

(tensor(3), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [23]:
## Arithmatic work for linear regression
y=w*x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [24]:
y.backward()   ##This will calculate all the graidents of Y with respect to W and b

In [27]:
print(f"dy/dx = {x.grad}")
print(f"dy/dw = {w.grad}")
print(f"dy/db = {b.grad}")
## dy/dx is Zero because x is our input and non trainable parameter

dy/dx = None
dy/dw = 6.0
dy/db = 3.0


In [35]:
## Tensor functions
## creating an empty matrix

t5=torch.full((5,5), 1)
print(t5)
t5=torch.full((5,5), 0)
print(t5)
t5=torch.full((5,5), -7)
print(t5)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])
tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])
tensor([[-7, -7, -7, -7, -7],
        [-7, -7, -7, -7, -7],
        [-7, -7, -7, -7, -7],
        [-7, -7, -7, -7, -7],
        [-7, -7, -7, -7, -7]])


In [38]:
t6=torch.cat((t3,t4))
print(t6)

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [41]:
t7=torch.sin(t6)       ## calculating sin values of t6
print(t7)

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794],
        [ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794],
        [ 0.6570,  0.9894,  0.4121]])


In [49]:
t8=t7.reshape(3,5)   ## Reshaping in pytorch
t8

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568, -0.9589],
        [-0.2794,  0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.2794,  0.6570,  0.9894,  0.4121]])

In [51]:
t9=torch.cos(t6)       ## calculating cos values of t6
print(t9)

tensor([[ 0.5403, -0.4161, -0.9900],
        [-0.6536,  0.2837,  0.9602],
        [ 0.5403, -0.4161, -0.9900],
        [-0.6536,  0.2837,  0.9602],
        [ 0.7539, -0.1455, -0.9111]])


In [52]:
##Converitng numpy array to tensor in pytorch
import numpy as np
x=np.array([[1,2,3],[7,8,9]])
x

array([[1, 2, 3],
       [7, 8, 9]])

In [53]:
y=torch.from_numpy(x)
y

tensor([[1, 2, 3],
        [7, 8, 9]])

In [54]:
## Converting tensor to numpy array
y.numpy()

array([[1, 2, 3],
       [7, 8, 9]])